# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Colm Doyle
description: "I'm Colm Doyle, a Software Engineer from Dublin, Ireland."
keywords: "colm, doyle, ios, facebook, developer, advocate, kitman"
url: http://cdoyle.me
baseurl: ""
cover_image: /images/og_cover_image.jpg
fb_app_id: 140479545983869
fb_admins: 260300016
twitter_id: colmisainmdom
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/colmdoyle/colmdoyle.github.io

# Author settings
author:
  name      : Colm Doyle
  job       : Software Engineer
  bio       : "I work on mobile projects at Kitman Labs."
  thumb     : /images/headshot264.jpg
  email     : hello@cdoyle.me
  url       : https://cdoyle.me
  github    : https://github.com/colmdoyle
  twitter   : https://twitter.com/colmisainmdom
  facebook  : https://facebook.com/colmdoyle
  linkedin  : https://ie.linkedin.com/in/colmdoyle

# navbar pages
navbar:
  # - slug: about
  #   title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  # - slug: blog
  #   title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
