# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colm Doyle
email: hello@cdoyle.me
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer with experience of multiple languages on codebases
  serving anything from 1 user to 1.3 billion users.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cdoyle.me" # the base hostname & protocol for your site
twitter_username: colmisainmdom
github_username:  colmdoyle

# Build settings
markdown: kramdown
