# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title: Colm Doyle
description: A Developer Relations professional in Dublin, Ireland.
tagline: A Developer Relations professional in Dublin, Ireland.
url: https://cdoyle.me
paginate: 5
baseurl: /

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

feed:
  path: /rss.xml

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Colm Doyle
  url: https://cdoyle.me
  email: hello@cdoyle.me
  twitter: colmisainmdom
  mastodon: https://mastodon.ie/@colmdoyle
  github: colmdoyle
  linkedin: colmdoyle

twitter:
  username: colmisainmdom

social:
  name: Colm Doyle
  links:
    - https://twitter.com/colmisainmdom
    - https://www.linkedin.com/in/colmdoyle/
    - https://github.com/colmdoyle
    - https://mastodon.ie/@colmdoyle

defaults:
  - scope:
      path: ""
    values:
      image: /public/photo.jpg
      layout: "post"
